name: Mermaid Diff Comment

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths:
      - "**.mmd"

jobs:
  comment-on-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Get Mermaid diff
        run: |
          # Get the list of added and modified .mmd files
          {
            # List added files
            git diff --name-status "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | grep '^A.*\.mmd$' | cut -f2
            # List modified files
            git diff --name-status "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | grep '^M.*\.mmd$' | cut -f2
          } > changed_mmd_files.txt

          # If no .mmd files were changed, skip the next steps
          if [[ ! -s changed_mmd_files.txt ]]; then
            echo "No Mermaid files were changed."
            exit 0
          fi

          # Create the comment file header
          echo "# Mermaid Diagram Changes" > pr_comment.md

          # Process each .mmd file
          while read -r file; do
            echo "Processing file: ${file}"

            # Check if file is newly added
            if git diff --name-status "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | grep -q "^A.*${file}$"; then
              echo "### New file: ${file}" >> pr_comment.md
              {
                echo "#### Content"
                echo "\`\`\`mermaid"
                cat "${file}"
                echo "\`\`\`"
              } >> pr_comment.md
            else
              # For modified files, show before and after
              echo "### Changes in ${file}" >> pr_comment.md
              {
                echo "#### Before"
                echo "\`\`\`mermaid"
                git show "${{ github.event.pull_request.base.sha }}:${file}" 2>/dev/null || echo "No previous version"
                echo "\`\`\`"
                echo "#### After"
                echo "\`\`\`mermaid"
                cat "${file}"
                echo "\`\`\`"
              } >> pr_comment.md
            fi
          done < changed_mmd_files.txt

      - name: Post comment to pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f pr_comment.md ]; then
            gh pr comment "${{ github.event.pull_request.number }}" --body-file pr_comment.md
          else
            echo "No Mermaid diagrams to comment on."
          fi
