name: typos

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
